### ISSUE TITLE
getting price

### ISSUE THREAD

**Issue by repane4229** [adanikel/BinanceExtensionCPP#54]
How would one get the currnet price of a symbol in a loop to compare it?
im not sure how to read the json from get_ticker

**Comment by adanikel** [comment]
hey @repane4229 
I wrote this example to illustrate how to use `get_ticker()`
https://github.com/adanikel/BinanceExtensionCPP/blob/master/examples/fetch_ticker_rest.cpp

Please make sure you have the `JsonCPP` dependency installed beforehand

**Comment by repane4229** [comment]
thanks so much

**Comment by adanikel** [comment]
Well, all REST methods throw `BadRequestREST` (custom library exception) if anything does not go well

You can start from catching that exception and use its method `what()` to see the traceback

**Comment by adanikel** [comment]
> thanks so much
> Would i need to check for null? and add try/catch? if it was in a loop

Can I close this? :)
