### ISSUE TITLE
Issue changing leverage type

### ISSUE THREAD

**Issue by gitkornel** [adanikel/BinanceExtensionCPP#56]
Hello, I'm getting this weird error when trying to compile:

`unresolved external symbol "public: class Json::Value __cdecl FuturesClient<class FuturesClientUSDT>::change_leverage(struct Params const *)" (?change_leverage@?$FuturesClient@VFuturesClientUSDT@@@@QEAA?AVValue@Json@@PEBUParams@@@Z)
`

My code:
```
std::string api_key{ "" };
std::string api_secret{ "" };

static FuturesClientUSDT my_client{ api_key, api_secret };
	
Params leverage_params{};
leverage_params.set_param("symbol", std::string(coin_name + "USDT"));
leverage_params.set_param("marginType", std::string("ISOLATED"));

std::cout << my_client.change_leverage(&leverage_params) << std::endl;
```

What am I doing wrong?

Best Regards.

**Comment by adanikel** [comment]
Found the issue, missing template function instantiations

pushing a fix, will update shortly

**Comment by adanikel** [comment]
@gitkornel 
tested locally and pushed a fix, please try the latest version and let me know if the issue was resolved

**Comment by gitkornel** [comment]
> 
> 
> @gitkornel
> tested locally and pushed a fix, please try the latest version and let me know if the issue was resolved

Yes, it works, awesome, big thanks!

**Comment by adanikel** [comment]
you're welcome!
feel free to put a star on my repo :)
