### ISSUE TITLE
Malformed klines

### ISSUE THREAD

**Issue by VitalyVaryvdin** [adanikel/BinanceExtensionCPP#59]
Getting klines I'm randomly receiving malformed kline object which is always last in response

```
],
        [
                1622667600000,
                "1.81059000",
                "1.81856000",
                "1.80819000",
                "1.81000000",
                "3131994.90000000",
                1622669399999,
                "5679722.58880500",
                8036,
                "1450047.50000000",
                "2630337.35958400",
                "0"
        ],
        [
                1622669400000,
                "1.81000000",
                null
        ]
][
        [
                1622671200000,
                "1.81245000",
                "1.81966000",
                "1.81000000",
                "1.81183000",
                "3189448.30000000",
                1622672999999,
                "5783082.03389300",
                7960,
                "1224261.90000000",
                "2220666.73000300",
                "0"
        ],
```

You can see it here between two good klines. Didn't happen with python-binance so i thought that might be library issue.
Json above is formed by doing multiple requests so in this case it's not last in the list.

**Comment by VitalyVaryvdin** [comment]
Found the issue.

Use of curl writefunction callback is incorrect. Callback might be called many times within single request.

> callback should return the number of bytes actually taken care of. If that amount differs from the amount passed to your callback function, it'll signal an error condition to the library.

Basically returning anything than `nmemb` will abort the request,.

Changed callback to only append response data to RequestHandler and then parsing json only after curl request completion. Gets rid of all of these issues

**Comment by adanikel** [comment]
Hey @VitalyVaryvdin 
Can you please the code snippet that solved this issue here?

**Comment by adanikel** [comment]
thanks for bringing this up, fixed and tested in https://github.com/adanikel/BinanceExtensionCPP/pull/60

**Comment by VitalyVaryvdin** [comment]
Sorry for late reply
Glad to be helpful :)
Yeah, im closing this now, just wanted to make sure you see it before closing
